#!groovy

String[] distributions = ['debian:bullseye', 'debian:bookworm', 'debian:trixie', 'ubuntu:focal', 'ubuntu:jammy', 'ubuntu:noble']

String vendor = 'vitexsoftware'
String distribution = ''
//String distroFamily = ''
String distroCodename = ''
String ver = ''

properties([
    copyArtifactPermission('*')
])
node() {
    ansiColor('xterm') {
        stage('SCM Checkout') {
            checkout scm
        }
    }
}

distributions.each {
    distribution = it

    println  "Dist:" + distribution

    def dist = distribution.split(':')
    distroCodename = dist[1]

    def buildImage = ''

    def artifacts = []

    node {
        ansiColor('xterm') {
            stage('Checkout ' + distribution) {
                checkout scm
                buildImage = docker.image(vendor + '/' + distribution)
                sh 'git checkout debian/changelog'
                def version = sh (
                    script: 'dpkg-parsechangelog --show-field Version',
                    returnStdout: true
                ).trim()
                ver = version + '.' + env.BUILD_NUMBER  + '~' + distroCodename
            }
            stage('Build ' + distribution) {
                buildImage.inside {
                    sh 'dch -b -v ' + ver  + ' "' + env.BUILD_TAG  + '"'
                    sh 'sudo apt-get update --allow-releaseinfo-change'
                    sh 'sudo chown jenkins:jenkins ..'
                    sh 'debuild-pbuilder  -i -us -uc -b'
                    sh 'mkdir -p $WORKSPACE/dist/debian/ ; rm -rf $WORKSPACE/dist/debian/* ; for deb in $(cat debian/files | awk \'{print $1}\'); do mv "../$deb" $WORKSPACE/dist/debian/; done'
                    artifacts = sh (
                        script: "cat debian/files | awk '{print \$1}'",
                        returnStdout: true
                    ).trim().split('\n')
                }
            }

            stage('Copy artifacts ' + distribution ) {
                buildImage.inside {
                    artifacts.each { deb_file ->
                        println "Copying artifact: " + deb_file
                        archiveArtifacts artifacts: 'dist/debian/' + deb_file
                        sh 'cp $WORKSPACE/dist/debian/' + deb_file + ' $WORKSPACE'
                    }
                }
            }
        }
    }
}

